apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  namespace: antivax
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: testjob
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - date; echo Hello!
      restartPolicy: OnFailure
